const ROLE_NAMES = {
  EMPLOYEE: "Сотрудник",
  DIRECTOR: "Директор",
  ADMIN: "Администратор",
  SYSADMIN: "Системный администратор",
};

const MODERATOR_ROLE_NAMES = [
  ROLE_NAMES.ADMIN,
  ROLE_NAMES.SYSADMIN,
];

const PIN_ROLE_NAMES = [
  ROLE_NAMES.DIRECTOR,
  ROLE_NAMES.ADMIN,
  ROLE_NAMES.SYSADMIN,
];

const DISPLAY_ROLE_NAMES = [
  ROLE_NAMES.DIRECTOR,
  ROLE_NAMES.ADMIN,
  ROLE_NAMES.SYSADMIN,
];

module.exports = {
  ROLE_NAMES,
  MODERATOR_ROLE_NAMES,
  PIN_ROLE_NAMES,
  DISPLAY_ROLE_NAMES,
};